DROP TABLE LOGARE CASCADE CONSTRAINTS;
/
DROP TABLE ARAGAZURI CASCADE CONSTRAINTS;
/
DROP TABLE ASPIRATOR CASCADE CONSTRAINTS;
/
DROP TABLE PRAJITOR_PAINE CASCADE CONSTRAINTS;
/
DROP TABLE MASINI_DE_SPALAT CASCADE CONSTRAINTS;
/
DROP TABLE MASINI_SPALAT_VASE CASCADE CONSTRAINTS;
/
DROP TABLE CUPTOR CASCADE CONSTRAINTS;
/
DROP TABLE ROBOT_BUCATARIE CASCADE CONSTRAINTS;
/

CREATE TABLE LOGARE (
    ID INT NOT NULL PRIMARY KEY,
    USERNAME VARCHAR2(30) NOT NULL ,
    PAROLA VARCHAR2(30) NOT NULL,
    NUME VARCHAR2(16) NOT NULL,
    PRENUME VARCHAR2(40) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL 
);
/
CREATE TABLE MASINI_DE_SPALAT(
    ID INT NOT NULL PRIMARY KEY,
    ID_USER INT NOT NULL,
    NUME VARCHAR2(30) NOT NULL,
    FIRMA VARCHAR2(20) NOT NULL,
    MODELS VARCHAR2(20) NOT NULL ,
    RPM INT,
    CAPACITATE VARCHAR2(15),
    CLASA VARCHAR2(5),
    PRET FLOAT NOT NULL,
    DATA_ADAUGARE DATE NOT NULL,
    CONSTRAINT FK_ID_USER_M FOREIGN KEY (ID_USER) REFERENCES LOGARE(ID)
);
/

CREATE TABLE MASINI_SPALAT_VASE(
    ID INT NOT NULL PRIMARY KEY,
    ID_USER INT NOT NULL,
    NUME VARCHAR2(30) NOT NULL,
    FIRMA VARCHAR2(20) NOT NULL,
    MODELS VARCHAR2(20) NOT NULL,
    CLASA VARCHAR2(5),
    CAPACITATE VARCHAR2(15),
    PRET FLOAT NOT NULL,
    DATA_ADAUGARE DATE NOT NULL,
    CONSTRAINT FK_ID_USER_MV FOREIGN KEY (ID_USER) REFERENCES LOGARE(ID)
);
/

CREATE TABLE PRAJITOR_PAINE(
    ID INT NOT NULL PRIMARY KEY,
    ID_USER INT NOT NULL,
    NUME VARCHAR2(30) NOT NULL,
    FIRMA VARCHAR2(30) NOT NULL,
    MODELS VARCHAR2(20) NOT NULL,
    CONSUM VARCHAR2(15),
    CAPACITATE VARCHAR2(15),
    CULOARE VARCHAR2(15),
    PRET FLOAT NOT NULL,
    DATA_ADAUGARE DATE NOT NULL,
    CONSTRAINT FK_ID_USER_PP FOREIGN KEY (ID_USER) REFERENCES LOGARE(ID)
);
/

CREATE TABLE ARAGAZURI (
    ID INT NOT NULL PRIMARY KEY,
    NUME VARCHAR2(30) ,
    FIRMA VARCHAR2(20) ,
    MODELS VARCHAR2(40) ,
    ARZATOARE INT,
    PRET FLOAT NOT NULL,
    DATA_ADAUGARE DATE NOT NULL,
    ID_USER INT NOT NULL ,
    CONSTRAINT FK_ID_USER_A FOREIGN KEY (ID_USER) REFERENCES LOGARE(ID)
);
/

CREATE TABLE ASPIRATOR (
    ID INT NOT NULL PRIMARY KEY,
    NUME VARCHAR2(30) NOT NULL,
    FIRMA VARCHAR2(20) NOT NULL,
    MODELS VARCHAR2(20) NOT NULL,
    CAPACITATE_SAC VARCHAR2(15),
    CONSUM VARCHAR2(15),
    PRET FLOAT NOT NULL,
    DATA_ADAUGARE DATE NOT NULL,
    ID_USER INT NOT NULL,
    CONSTRAINT FK_ID_USER_AS FOREIGN KEY (ID_USER) REFERENCES LOGARE(ID)
);
/

CREATE TABLE CUPTOR (
    ID INT NOT NULL PRIMARY KEY,
    NUME VARCHAR2(30) NOT NULL,
    FIRMA VARCHAR2(20) NOT NULL,
    MODELS VARCHAR2(20) NOT NULL,
    CAPACITATE VARCHAR2(15),
    CONSUM VARCHAR2(15),
    CULOARE VARCHAR2(10),
    PRET FLOAT NOT NULL,
    DATA_ADAUGARE DATE NOT NULL,
    ID_USER INT NOT NULL,
    CONSTRAINT FK_ID_USER_C FOREIGN KEY (ID_USER) REFERENCES LOGARE(ID)
);
/

CREATE TABLE ROBOT_BUCATARIE (
    ID INT NOT NULL PRIMARY KEY,
    NUME VARCHAR2(30) NOT NULL,
    FIRMA VARCHAR2(20) NOT NULL,
    MODELS VARCHAR2(20) NOT NULL,
    NR_VITEZE INT,
    CONSUM VARCHAR2(15),
    VOLUM VARCHAR2(10),
    PRET FLOAT NOT NULL,
    DATA_ADAUGARE DATE NOT NULL,
    ID_USER INT NOT NULL,
    CONSTRAINT FK_ID_USER_RB FOREIGN KEY (ID_USER) REFERENCES LOGARE(ID)
);

/
SET SERVEROUTPUT ON;
DECLARE
    TYPE VARR IS VARRAY(1000) OF VARCHAR(255);
    LISTA_NUME VARR := VARR('ABABEI','ACASANDREI','ADASCALITEI','AFANASIE','AGAFITEI','AGAPE','AIOANEI','ALEXANDRESCU','ALEXANDRU','ALEXE','ALEXII','AMARGHIOALEI','AMBROCI','ANDONESEI','ANDREI','ANDRIAN','ANDRICI','ANDRONIC','ANDROS','ANGHELINA','ANITA','ANTOCHI','ANTONIE','APETREI','APOSTOL','ARHIP','ARHIRE','ARTENI','ARVINTE','ASAFTEI','ASOFIEI','AUNGURENCI','AVADANEI','AVRAM','BABEI','BACIU','BAETU','BALAN','BALICA','BANU','BARBIERU','BARZU','BAZGAN','BEJAN','BEJENARU','BELCESCU','BELCIUGANU','BENCHEA','BILAN','BIRSANU','BIVOL','BIZU','BOCA','BODNAR','BOISTEAN','BORCAN','BORDEIANU','BOTEZATU','BRADEA','BRAESCU','BUDACA','BULAI','BULBUC','BURLACU','BURLOIU','BURSUC','BUTACU','BUTE','BUZA','CALANCEA','CALINESCU','CAPUSNEANU','CARAIMAN','CARBUNE','CARP','CATANA','CATIRU','CATONOIU','CAZACU','CAZAMIR','CEBERE','CEHAN','CERNESCU','CHELARU','CHELMU','CHELMUS','CHIBICI','CHICOS','CHILABOC','CHILE','CHIRIAC','CHIRILA','CHISTOL','CHITIC','CHMILEVSKI','CIMPOESU','CIOBANU','CIOBOTARU','CIOCOIU','CIOFU','CIORNEI','CITEA','CIUCANU','CLATINICI','CLIM','COBUZ','COCA','COJOCARIU','COJOCARU','CONDURACHE','CORCIU','CORDUNEANU','CORFU','CORNEANU','CORODESCU','COSERU','COSNITA','COSTAN','COVATARIU','COZMA','COZMIUC','CRACIUNAS','CRAINICEANU','CREANGA','CRETU','CRISTEA','CRUCERESCU','CUMPATA','CURCA','CUSMULIUC','DAMIAN','DAMOC','DANELIUC','DANIEL','DANILA','DARIE','DASCALESCU','DASCALU','DIACONU','DIMA','DIMACHE','DINU','DOBOS','DOCHITEI','DOCHITOIU','DODAN','DOGARU','DOMNARU','DORNEANU','DRAGAN','DRAGOMAN','DRAGOMIR','DRAGOMIRESCU','DUCEAC','DUDAU','DURNEA','EDU','EDUARD','EUSEBIU','FEDELES','FERESTRAOARU','FILIBIU','FILIMON','FILIP','FLORESCU','FOLVAITER','FRUMOSU','FRUNZA','GALATANU','GAVRILITA','GAVRILIUC','GAVRILOVICI','GHERASE','GHERCA','GHERGU','GHERMAN','GHIBIRDIC','GIOSANU','GITLAN','GIURGILA','GLODEANU','GOLDAN','GORGAN','GRAMA','GRIGORE','GRIGORIU','GROSU','GROZAVU','GURAU','HABA','HARABULA','HARDON','HARPA','HERDES','HERSCOVICI','HOCIUNG','HODOREANU','HOSTIUC','HUMA','HUTANU','HUZUM','IACOB','IACOBUTA','IANCU','ICHIM','IFTIMESEI','ILIE','INSURATELU','IONESEI','IONESI','IONITA','IORDACHE','IORDACHE-TIROIU','IORDAN','IOSUB','IOVU','IRIMIA','IVASCU','JECU','JITARIUC','JITCA','JOLDESCU','JURAVLE','LARION','LATES','LATU','LAZAR','LELEU','LEON','LEONTE','LEUCIUC','LEUSTEAN','LUCA','LUCACI','LUCASI','LUNCASU','LUNGEANU','LUNGU','LUPASCU','LUPU','MACARIU','MACOVESCHI','MAFTEI','MAGANU','MANGALAGIU','MANOLACHE','MANOLE','MARCU','MARINOV','MARTINAS','MARTON','MATACA','MATCOVICI','MATEI','MATIES','MATRANA','MAXIM','MAZAREANU','MAZILU','MAZUR','MELNICIUC','MICU','MIHAELA','MIHAI','MIHAILA','MIHAILESCU','MIHALACHI','MIHALCEA','MIHOCIU','MILUT','MINEA','MINGHEL','MINUTI','MIRON','MITAN','MOISA','MONIRY-ABYANEH','MORARESCU','MOROSANU','MOSCU','MOTRESCU','MOTROI','MUNTEANU','MURARASU','MUSCA','MUTESCU','NASTACA','NECHITA','NEGHINA','NEGRUS','NEGRUSER','NEGRUTU','NEMTOC','NETEDU','NICA','NICU','OANA','OLANUTA','OLARASU','OLARIU','OLARU','ONU','OPARIUC','OPREA','OSTAFE','OTROCOL','PALIHOVICI','PANTIRU','PANTIRUC','PAPARUZ','PASCARU','PATACHI','PATRAS','PATRICHE','PERCIUN','PERJU','PETCU','PILA','PINTILIE','PIRIU','PLATON','PLUGARIU','PODARU','POENARIU','POJAR','POPA','POPESCU','POPOVICI','POPUTOAIA','POSTOLACHE','PREDOAIA','PRISECARU','PROCOP','PRODAN','PUIU','PURICE','RACHIERU','RAZVAN','REUT','RISCANU','RIZA','ROBU','ROMAN','ROMANESCU','ROMANIUC','ROSCA','RUSU','SAMSON','SANDU','SANDULACHE','SAVA','SAVESCU','SCHIFIRNET','SCORTANU','SCURTU','SFARGHIU','SILITRA','SIMIGANOSCHI','SIMION','SIMIONESCU','SIMIONESEI','SIMON','SITARU','SLEGHEL','SOFIAN','SOFICU','SPARHAT','SPIRIDON','STAN','STAVARACHE','STEFAN','STEFANITA','STINGACIU','STIUFLIUC','STOIAN','STOICA','STOLERU','STOLNICEANU','STOLNICU','STRAINU','STRIMTU','SUHANI','TABUSCA','TALIF','TANASA','TECLICI','TEODORESCU','TESU','TIFREA','TIMOFTE','TINCU','TIRPESCU','TOADER','TOFAN','TOMA','TONCU','TRIFAN','TUDOSA','TUDOSE','TUDURI','TUIU','TURCU','ULINICI','UNGHIANU','UNGUREANU','URSACHE','URSACHI','URSE','URSU','VARLAN','VARTENIUC','VARVAROI','VASILACHE','VASILIU','VENTANIUC','VICOL','VIDRU','VINATORU','VLAD','VOAIDES','VRABIE','VULPESCU','ZAMOSTEANU','ZAZULEAC');
    LISTA_PRENUME_FETE VARR := VARR('ADINA','ALEXANDRA','ALINA','ANA','ANCA','ANDA','ANDRA','ANDREEA','ANDREIA','ANTONIA','BIANCA','CAMELIA','CLAUDIA','CODRINA','CRISTINA','DANIELA','DARIA','DELIA','DENISA','DIANA','ECATERINA','ELENA','ELEONORA','ELISA','EMA','EMANUELA','EMMA','GABRIELA','GEORGIANA','ILEANA','ILONA','IOANA','IOLANDA','IRINA','IULIA','IULIANA','LARISA','LAURA','LOREDANA','MADALINA','MALINA','MANUELA','MARIA','MIHAELA','MIRELA','MONICA','OANA','PAULA','PETRUTA','RALUCA','SABINA','SANZIANA','SIMINA','SIMONA','STEFANA','STEFANIA','TAMARA','TEODORA','THEODORA','VASILICA','XENA');
    LISTA_PRENUME_BAIETI VARR := VARR('ADRIAN','ALEX','ALEXANDRU','ALIN','ANDREAS','ANDREI','AURELIAN','BENIAMIN','BOGDAN','CAMIL','CATALIN','CEZAR','CIPRIAN','CLAUDIU','CODRIN','CONSTANTIN','CORNELIU','COSMIN','COSTEL','CRISTIAN','DAMIAN','DAN','DANIEL','DANUT','DARIUS','DENISE','DIMITRIE','DORIAN','DORIN','DRAGOS','DUMITRU','EDUARD','ELVIS','EMIL','ERVIN','EUGEN','EUSEBIU','FABIAN','FILIP','FLORIAN','FLORIN','GABRIEL','GEORGE','GHEORGHE','GIANI','GIULIO','IAROSLAV','ILIE','IOAN','ION','IONEL','IONUT','IOSIF','IRINEL','IULIAN','IUSTIN','LAURENTIU','LIVIU','LUCIAN','MARIAN','MARIUS','MATEI','MIHAI','MIHAIL','NICOLAE','NICU','NICUSOR','OCTAVIAN','OVIDIU','PAUL','PETRU','PETRUT','RADU','RARES','RAZVAN','RICHARD','ROBERT','ROLAND','ROLLAND','ROMANESCU','SABIN','SAMUEL','SEBASTIAN','SERGIU','SILVIU','STEFAN','TEODOR','TEOFIL','THEODOR','TUDOR','VADIM','VALENTIN','VALERIU','VASILE','VICTOR','VLAD','VLADIMIR','VLADUT');
    LISTA_FIRME_ARAGAZ VARR := VARR('GORENJE','ELECTROLUX','BEKO','ZANUSSI','ARCTIC','HANSA','MYRIA','WHIRLPOOL','AEG','SHARP','BOSCH','INDESIT','METALICA','HEINNER');
    LISTA_FIRME_ASPIRATOR VARR := VARR('ROWENTA','PHILIPS','BOSCH','HOOVER','ELECTROLUX','KARCHER','GORENJE','SAMSUNG','BEKO','MYRIA','DYSON','ZELMER','DAEWOO','IROBOT','THOMAS','DORT DEBIL','VORTEX','MEDIASHOP','WHIRLPOOL','TEFAL','SHARP','XIAOMI','HEINNER','VAX');
    LISTA_FIRME_CUPTOR VARR := VARR('SAMSUNG','MYRIA','TEFAL','DAEWOO','BEKO','GORENJE','SHARP','OURSSON','BBK','PARASONIC');
    LISTA_FIRME_MS VARR := VARR('GORENJE','BEKO','SAMSUNG','CANDY','ELECTROLUX','BOSCH','SHARP','LG','WHIRLPOOL','ARCTIC','INDESIT','MYRIA','AEG','GRUNDIG','HOTPOINT','HEINNER');
    LISTA_FIRME_MSV VARR := VARR('BOSCH','BEKO','CANDY','GORENJE','ELECTROLUX','WHIRLPOOL','SHARP','AEG','HOTPOINT','GRUDIG','MYRIA','ARCTIC','HANSA');
    LISTA_FIRME_PP VARR := VARR('BOSCH','TEFAL','GORENJE','KENWOOD','PHILIPS','ELECTROLUX','KITCHENAID','MYRIA','ROHNSON','BEKO');
    LISTA_FIRME_RB VARR := VARR('BOSCH','TEFAL','GORENJE','KENWOOD','PHILIPS','ELECTROLUX','KITCHENAID','MYRIA','RUSSELL HOBBS','ROHNSON','BEKO');
    LISTA_CULORI VARR := VARR('ROZ','ROSU','VERDE','GALBEN','ALB','NEGRU','MOV','BLEUMARIN');
    LISTA_AN VARR := VARR('2016','2017','2018');
    LISTA_LUNA VARR := VARR('IANUARIE','FEBRUARIE','MARTIE','APRILIE','MAI','IUNIE','IULIE','AUGUST','SEPTEMBRIE','OCTOMBRIE','NOIEMBRIE','DECEMBRIE');
    LISTA_ZILE VARR := VARR('01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31');
    LISTA_MODELE VARR := VARR('X423','DF4','455','DVV','ACDL','X54','MAC2','ASF232','PODS1','PODS2','LAC2','HDD','LAAS','ERD','MMP','AEX','MAX','PRO','LUX','CMMD15','AD650','MA234','ZAD12','CR324','BAF202','MAXDD20');
    LISTA_CLASE VARR := VARR('A','A+','A++','A+++');
    
    V_NUME VARCHAR(255);
    V_PRENUME VARCHAR(255);
    V_PRENUME1 VARCHAR(255);
    V_PRENUME2 VARCHAR(255);
    V_EMAIL VARCHAR(255);
    V_PAROLA VARCHAR(255);
    V_USERNAME VARCHAR(255);
    V_TEMP INT;
    V_NUME_PRODUS VARCHAR(255);
    V_FIRMA VARCHAR(255);
    V_FIRMA1 VARCHAR(255);
    V_MODELS VARCHAR(255);
    V_PRET FLOAT;
    V_DATA_ADAUGARE DATE;
    V_ARZATOARE INT;
    V_TEMP1 INT ;
    V_TEMP2 INT;
    V_FILTRARE INT;
    V_CONSUM VARCHAR2(255);
    V_CAPACITATE VARCHAR2(255);
    V_CULOARE VARCHAR2(255);
    V_INALTIME INT;
    V_LATIME INT;
    V_CLASA VARCHAR2(255);
    V_RPM NUMBER;
    V_VITEZE INT;
    
BEGIN
    
     DBMS_OUTPUT.PUT_LINE('INSERAREA A 1000 USERI...');
    FOR V_I IN 1..1000 LOOP
        V_NUME := LISTA_NUME(TRUNC(DBMS_RANDOM.VALUE(0,LISTA_NUME.COUNT))+1);
      IF (DBMS_RANDOM.VALUE(0,100)<50) THEN      
         V_PRENUME1 := LISTA_PRENUME_FETE(TRUNC(DBMS_RANDOM.VALUE(0,LISTA_PRENUME_FETE.COUNT))+1);
         LOOP
            V_PRENUME2 := LISTA_PRENUME_FETE(TRUNC(DBMS_RANDOM.VALUE(0,LISTA_PRENUME_FETE.COUNT))+1);
            EXIT WHEN V_PRENUME1<>V_PRENUME2;
         END LOOP;
       ELSE
         V_PRENUME1 := LISTA_PRENUME_BAIETI(TRUNC(DBMS_RANDOM.VALUE(0,LISTA_PRENUME_BAIETI.COUNT))+1);
         LOOP
            V_PRENUME2 := LISTA_PRENUME_BAIETI(TRUNC(DBMS_RANDOM.VALUE(0,LISTA_PRENUME_BAIETI.COUNT))+1);
            EXIT WHEN V_PRENUME1<>V_PRENUME2;
         END LOOP;       
       END IF;
     
     IF (DBMS_RANDOM.VALUE(0,100)<60) THEN  
        IF LENGTH(V_PRENUME1 || ' ' || V_PRENUME2) <= 20 THEN
          V_PRENUME := V_PRENUME1 || ' ' || V_PRENUME2;
        END IF;
        ELSE 
           V_PRENUME:=V_PRENUME1;
      END IF;
      V_USERNAME := LOWER(V_PRENUME1 || '_' ||V_NUME || TO_CHAR(FLOOR(DBMS_RANDOM.VALUE(1,9999))));
      V_PAROLA := LOWER(V_NUME)||UPPER(V_PRENUME1)||TO_CHAR(FLOOR(DBMS_RANDOM.VALUE(1,999)));
      
      V_TEMP:='';
      V_EMAIL := LOWER(V_NUME ||'.'|| V_PRENUME1);
      LOOP         
         SELECT COUNT(*) INTO V_TEMP FROM LOGARE WHERE EMAIL = V_EMAIL||V_TEMP;
         EXIT WHEN V_TEMP=0;
         V_TEMP :=  TRUNC(DBMS_RANDOM.VALUE(0,100));
      END LOOP;    
      
      IF (TRUNC(DBMS_RANDOM.VALUE(0,4))=0) THEN V_EMAIL := V_EMAIL ||'@gmail.com';
         ELSIF (TRUNC(DBMS_RANDOM.VALUE(0,4))=1) THEN V_EMAIL := V_EMAIL ||'@gmail.com';
         ELSIF (TRUNC(DBMS_RANDOM.VALUE(0,4))=2) THEN V_EMAIL := V_EMAIL ||'@yahoo.com';
         ELSIF (TRUNC(DBMS_RANDOM.VALUE(0,4))=3) THEN V_EMAIL := V_EMAIL ||'@hotmail.com';
         ELSE V_EMAIL := V_EMAIL || '@outlook.com';
      END IF;
      
    INSERT INTO LOGARE VALUES(V_I, V_USERNAME,V_PAROLA,V_NUME,V_PRENUME,V_EMAIL);
    
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE('INSERAREA A 1000 USERI... GATA !');
	
 
 DBMS_OUTPUT.PUT_LINE('INSERAREA A 1500 ARAGAZURI...');
    
    SELECT COUNT(ID) INTO V_TEMP FROM LOGARE;
    FOR V_I IN 1..1500 LOOP
        LOOP
            V_TEMP1 := TRUNC(DBMS_RANDOM.VALUE(0,V_TEMP-1))+1;
            V_TEMP2 := TRUNC(DBMS_RANDOM.VALUE(0,V_TEMP-1))+1;
            EXIT WHEN V_TEMP1<>V_TEMP2;
        END LOOP;

         V_NUME := 'ARAGAZ ';
         V_FIRMA := LISTA_FIRME_ARAGAZ(TRUNC(DBMS_RANDOM.VALUE(0,LISTA_FIRME_ARAGAZ.COUNT))+1);
         V_MODELS := DBMS_RANDOM.STRING('X',4)||TRUNC(DBMS_RANDOM.VALUE(10,999));
        V_PRET := ROUND(DBMS_RANDOM.VALUE(1000,2500),2);
        V_ARZATOARE := TRUNC(DBMS_RANDOM.VALUE(2,4))+1;
        V_DATA_ADAUGARE := TO_DATE('01-01-2017','MM-DD-YYYY')+TRUNC(DBMS_RANDOM.VALUE(0,700));
        INSERT INTO ARAGAZURI VALUES(V_I, V_NUME,V_FIRMA,V_MODELS,V_ARZATOARE,V_PRET,V_DATA_ADAUGARE,V_TEMP1);

    END LOOP;
    DBMS_OUTPUT.PUT_LINE('INSERAREA ARAGAZURILOR GATA!');
    
    DBMS_OUTPUT.PUT_LINE('INSERAREA A 1000 ASPIRATOARE...');
    
    SELECT COUNT(ID) INTO V_TEMP FROM LOGARE;
    FOR V_I IN 1..1000 LOOP
        LOOP
            V_TEMP1 := TRUNC(DBMS_RANDOM.VALUE(0,V_TEMP-1))+1;
            V_TEMP2 := TRUNC(DBMS_RANDOM.VALUE(0,V_TEMP-1))+1;
            EXIT WHEN V_TEMP1<>V_TEMP2;
        END LOOP;

         V_NUME := 'ASPIRATOR ';
         V_FIRMA := LISTA_FIRME_ASPIRATOR(TRUNC(DBMS_RANDOM.VALUE(0,LISTA_FIRME_ASPIRATOR.COUNT))+1);
         V_MODELS := DBMS_RANDOM.STRING('X',4)||TRUNC(DBMS_RANDOM.VALUE(10,999));
        V_PRET := ROUND(DBMS_RANDOM.VALUE(800,2500),2);
       V_DATA_ADAUGARE := TO_DATE('01-01-2017','MM-DD-YYYY')+TRUNC(DBMS_RANDOM.VALUE(0,700));
        V_CONSUM := TO_CHAR(TRUNC(DBMS_RANDOM.VALUE(500,1200)))||' W' ;
        V_CAPACITATE := TO_CHAR(ROUND(DBMS_RANDOM.VALUE(1,4),1))||' L';
        INSERT INTO ASPIRATOR VALUES(V_I, V_NUME,V_FIRMA,V_MODELS,V_CAPACITATE,V_CONSUM,V_PRET,V_DATA_ADAUGARE,V_TEMP1);

    END LOOP;
    DBMS_OUTPUT.PUT_LINE('INSERAREA ASPIRATOARELOR GATA!');
     DBMS_OUTPUT.PUT_LINE('INSERAREA A 1000 CUPTOARE CU MICROUNDE...');
    
    SELECT COUNT(ID) INTO V_TEMP FROM LOGARE;
    FOR V_I IN 1..1000 LOOP
        LOOP
            V_TEMP1 := TRUNC(DBMS_RANDOM.VALUE(0,V_TEMP-1))+1;
            V_TEMP2 := TRUNC(DBMS_RANDOM.VALUE(0,V_TEMP-1))+1;
            EXIT WHEN V_TEMP1<>V_TEMP2;
        END LOOP;

         V_NUME := 'CUPTOR CU MICROUNDE ';
         V_FIRMA := LISTA_FIRME_CUPTOR(TRUNC(DBMS_RANDOM.VALUE(0,LISTA_FIRME_CUPTOR.COUNT))+1);
         V_MODELS := DBMS_RANDOM.STRING('X',3)||TRUNC(DBMS_RANDOM.VALUE(10,999));
        V_PRET := ROUND(DBMS_RANDOM.VALUE(100,2100),2);
        V_DATA_ADAUGARE := TO_DATE('01-01-2017','MM-DD-YYYY')+TRUNC(DBMS_RANDOM.VALUE(0,700));
        V_CONSUM := TO_CHAR(TRUNC(DBMS_RANDOM.VALUE(700,1200)))||' W' ;
        V_CAPACITATE := TO_CHAR(ROUND(DBMS_RANDOM.VALUE(1,4),1))||' L';
        V_CULOARE := LISTA_CULORI(TRUNC(DBMS_RANDOM.VALUE(0,LISTA_CULORI.COUNT))+1);
        INSERT INTO CUPTOR VALUES(V_I, V_NUME,V_FIRMA,V_MODELS,V_CAPACITATE,V_CONSUM,V_CULOARE,V_PRET,V_DATA_ADAUGARE,V_TEMP1);

    END LOOP;
    DBMS_OUTPUT.PUT_LINE('INSERAREA CUPTOARELOR CU MICROUNDE GATA!');
    
    DBMS_OUTPUT.PUT_LINE('INSERAREA A 1100 MASINI DE SPALAT...');
    
    SELECT COUNT(ID) INTO V_TEMP FROM LOGARE;
    FOR V_I IN 1..1100 LOOP
        LOOP
            V_TEMP1 := TRUNC(DBMS_RANDOM.VALUE(0,V_TEMP-1))+1;
            V_TEMP2 := TRUNC(DBMS_RANDOM.VALUE(0,V_TEMP-1))+1;
            EXIT WHEN V_TEMP1<>V_TEMP2;
        END LOOP;

         V_NUME := 'MASINA DE SPALAT ';
         V_FIRMA := LISTA_FIRME_MS(TRUNC(DBMS_RANDOM.VALUE(0,LISTA_FIRME_MS.COUNT))+1);
         V_MODELS := DBMS_RANDOM.STRING('X',4)||TRUNC(DBMS_RANDOM.VALUE(10,999));
        V_PRET := ROUND(DBMS_RANDOM.VALUE(1200,5000),2);
        V_DATA_ADAUGARE := TO_DATE('01-01-2017','MM-DD-YYYY')+TRUNC(DBMS_RANDOM.VALUE(0,700));
        V_CAPACITATE := TO_CHAR(ROUND(DBMS_RANDOM.VALUE(7,11)))||' KG';
        V_RPM := ROUND(DBMS_RANDOM.VALUE(1000,1400));
        V_CLASA := LISTA_CLASE(TRUNC(DBMS_RANDOM.VALUE(0,LISTA_CLASE.COUNT))+1);
        INSERT INTO MASINI_DE_SPALAT VALUES(V_I, V_TEMP1,V_NUME,V_FIRMA,V_MODELS,V_RPM,V_CAPACITATE,V_CLASA,V_PRET,V_DATA_ADAUGARE);

    END LOOP;
    DBMS_OUTPUT.PUT_LINE('INSERAREA MASINILOR DE SPALAT GATA!');
    
    DBMS_OUTPUT.PUT_LINE('INSERAREA A 1200 MASINI DE SPALAT VASE...');
    
    SELECT COUNT(ID) INTO V_TEMP FROM LOGARE;
    FOR V_I IN 1..1200 LOOP
        LOOP
            V_TEMP1 := TRUNC(DBMS_RANDOM.VALUE(0,V_TEMP-1))+1;
            V_TEMP2 := TRUNC(DBMS_RANDOM.VALUE(0,V_TEMP-1))+1;
            EXIT WHEN V_TEMP1<>V_TEMP2;
        END LOOP;

         V_NUME := 'MASINA DE SPALAT VASE ';
         V_FIRMA := LISTA_FIRME_MSV(TRUNC(DBMS_RANDOM.VALUE(0,LISTA_FIRME_MSV.COUNT))+1);
         V_MODELS := DBMS_RANDOM.STRING('X',4)||TRUNC(DBMS_RANDOM.VALUE(10,999));
        V_PRET := ROUND(DBMS_RANDOM.VALUE(1200,5000),2);
        V_DATA_ADAUGARE := TO_DATE('01-01-2017','MM-DD-YYYY')+TRUNC(DBMS_RANDOM.VALUE(0,700));
        V_CAPACITATE := TO_CHAR(ROUND(DBMS_RANDOM.VALUE(10,20)))||' SETURI';
        V_CLASA := LISTA_CLASE(TRUNC(DBMS_RANDOM.VALUE(0,LISTA_CLASE.COUNT))+1);
        INSERT INTO MASINI_SPALAT_VASE VALUES(V_I, V_TEMP1,V_NUME,V_FIRMA,V_MODELS,V_CLASA,V_CAPACITATE,V_PRET,V_DATA_ADAUGARE);

    END LOOP;
    DBMS_OUTPUT.PUT_LINE('INSERAREA MASINILOR DE SPALAT VASE GATA!');
    
    DBMS_OUTPUT.PUT_LINE('INSERAREA A 900 PRAITOARE DE PAINE...');
    
    SELECT COUNT(ID) INTO V_TEMP FROM LOGARE;
    FOR V_I IN 1..900 LOOP
        LOOP
            V_TEMP1 := TRUNC(DBMS_RANDOM.VALUE(0,V_TEMP-1))+1;
            V_TEMP2 := TRUNC(DBMS_RANDOM.VALUE(0,V_TEMP-1))+1;
            EXIT WHEN V_TEMP1<>V_TEMP2;
        END LOOP;

         V_NUME := 'PRAJITOR DE PAINE ';
         V_FIRMA := LISTA_FIRME_PP(TRUNC(DBMS_RANDOM.VALUE(0,LISTA_FIRME_PP.COUNT))+1);
         V_MODELS := DBMS_RANDOM.STRING('X',4)||TRUNC(DBMS_RANDOM.VALUE(10,999));
        V_PRET := ROUND(DBMS_RANDOM.VALUE(50,600),2);
        V_DATA_ADAUGARE := TO_DATE('01-01-2017','MM-DD-YYYY')+TRUNC(DBMS_RANDOM.VALUE(0,700));
        V_CONSUM := TO_CHAR(ROUND(DBMS_RANDOM.VALUE(800,1800)))||' W';
        V_CAPACITATE := TO_CHAR(ROUND(DBMS_RANDOM.VALUE(2,4)))||' FELII';
        V_CULOARE := LISTA_CULORI(TRUNC(DBMS_RANDOM.VALUE(0,LISTA_CULORI.COUNT))+1);
        INSERT INTO PRAJITOR_PAINE VALUES(V_I, V_TEMP1,V_NUME,V_FIRMA,V_MODELS,V_CONSUM,V_CAPACITATE,V_CULOARE,V_PRET,V_DATA_ADAUGARE);

    END LOOP;
    DBMS_OUTPUT.PUT_LINE('INSERAREA PRAJITOARELOR DE PAINE GATA!');
    
    DBMS_OUTPUT.PUT_LINE('INSERAREA A 1000 ROBOTI DE BUCATARIE...');
    
    SELECT COUNT(ID) INTO V_TEMP FROM LOGARE;
    FOR V_I IN 1..1000 LOOP
        LOOP
            V_TEMP1 := TRUNC(DBMS_RANDOM.VALUE(0,V_TEMP-1))+1;
            V_TEMP2 := TRUNC(DBMS_RANDOM.VALUE(0,V_TEMP-1))+1;
            EXIT WHEN V_TEMP1<>V_TEMP2;
        END LOOP;

         V_NUME := 'ROBOT DE BUCATARIE ';
         V_FIRMA := LISTA_FIRME_RB(TRUNC(DBMS_RANDOM.VALUE(0,LISTA_FIRME_RB.COUNT))+1);
         V_MODELS := DBMS_RANDOM.STRING('X',4)||TRUNC(DBMS_RANDOM.VALUE(10,999));
        V_PRET := ROUND(DBMS_RANDOM.VALUE(50,600),2);
        V_DATA_ADAUGARE := TO_DATE('01-01-2017','MM-DD-YYYY')+TRUNC(DBMS_RANDOM.VALUE(0,700));
        V_CONSUM := TO_CHAR(ROUND(DBMS_RANDOM.VALUE(800,1800)))||' W';
        V_CAPACITATE := TO_CHAR(ROUND(DBMS_RANDOM.VALUE(1,6)))||' L';
        V_CULOARE := LISTA_CULORI(TRUNC(DBMS_RANDOM.VALUE(0,LISTA_CULORI.COUNT))+1);
        V_VITEZE := ROUND(DBMS_RANDOM.VALUE(3,6));
        INSERT INTO ROBOT_BUCATARIE VALUES(V_I,V_NUME,V_FIRMA,V_MODELS,V_VITEZE,V_CONSUM,V_CAPACITATE,V_PRET,V_DATA_ADAUGARE, V_TEMP1);

    END LOOP;
    DBMS_OUTPUT.PUT_LINE('INSERAREA ROBOTILOR DE BUCATARIE GATA!');

END;